#!/bin/bash

# VSCode Server Stack Deployment Script
# This script deploys the VSCode Server CloudFormation stack with S3 bucket support

# set -e

# Default values
PROJECT_NAME="ax-on-mastery"
INSTANCE_TYPE="m8i.2xlarge"
VSCODE_SERVER_VERSION="4.109.2"
DEPLOY_PROJECT_RESOURCE="True"
DEPLOY_INIT_MINIMAL="False"
STACK_NAME="VSCodeServerStack"
AUTO_CONFIRM=false

# Parse command line arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --project-name)
      PROJECT_NAME="$2"
      shift 2
      ;;
    --instance-type)
      INSTANCE_TYPE="$2"
      shift 2
      ;;
    --vscode-server-version)
      VSCODE_SERVER_VERSION="$2"
      shift 2
      ;;
    --deploy-project-resource)
      DEPLOY_PROJECT_RESOURCE="$2"
      shift 2
      ;;
    --deploy-init-minimal)
      DEPLOY_INIT_MINIMAL="$2"
      shift 2
      ;;
    --stack-name)
      STACK_NAME="$2"
      shift 2
      ;;
    --yes)
      AUTO_CONFIRM=true
      shift
      ;;
    --help|-h)
      echo "Usage: $0 [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --project-name NAME              Project name (default: ax-on-mastery)"
      echo "  --instance-type TYPE             EC2 instance type (default: m5.2xlarge)"
      echo "  --vscode-server-version VERSION  VSCode Server version (default: 4.109.2)"
      echo "  --deploy-project-resource BOOL   Deploy project resources (default: True)"
      echo "  --deploy-init-minimal BOOL       Deploy minimal initialization (default: False)"
      echo "  --stack-name NAME                CloudFormation stack name (default: VSCodeServerStack)"
      echo "  --yes                            Skip confirmation prompts (auto-confirm)"
      echo "  --help, -h                       Show this help message"
      echo ""
      echo "Environment variables required:"
      echo "  GITHUB_TOKEN           GitHub Personal Access Token"
      echo "  REMOTE_SSH_PUBLIC_KEY  SSH public key for Remote SSH"
      echo "  OPENAI_API_KEY         OpenAI API Key"
      echo ""
      echo "Environment variables (auto-generated by script):"
      echo "  AWS_ACCESS_KEY_ID         Generated from APIuser"
      echo "  AWS_SECRET_ACCESS_KEY     Generated from APIuser"
      echo "  AWS_BEARER_TOKEN_BEDROCK  Generated from APIuser for Bedrock"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      echo "Use --help for usage information"
      exit 1
      ;;
  esac
done

echo "=========================================="
echo "Checking for existing APIuser..."
echo "=========================================="

if aws iam get-user --user-name APIuser &>/dev/null; then
    echo "⚠️ IAM User 'APIuser' already exists"

    if [ "$AUTO_CONFIRM" = false ]; then
        read -p "Do you want to delete the existing APIuser? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "Aborting..."
            exit 1
        fi
    else
        echo "Auto-confirm enabled. Proceeding with deletion..."
    fi

    echo "Deleting existing APIuser..."

    # Delete access keys
    echo "  Deleting access keys..."
    ACCESS_KEYS=$(aws iam list-access-keys --user-name APIuser --query 'AccessKeyMetadata[].AccessKeyId' --output text)
    if [ -n "$ACCESS_KEYS" ]; then
        for key in $ACCESS_KEYS; do
            aws iam delete-access-key --user-name APIuser --access-key-id "$key"
            echo "🔑 Access key deleted: $key"
        done
    else
        echo "📌 No access keys to delete"
    fi

    # Delete service-specific credentials
    echo "  Deleting service-specific credentials..."
    SERVICE_CREDS=$(aws iam list-service-specific-credentials --user-name APIuser --query 'ServiceSpecificCredentials[].ServiceSpecificCredentialId' --output text 2>/dev/null || echo "")
    if [ -n "$SERVICE_CREDS" ]; then
        for cred in $SERVICE_CREDS; do
            aws iam delete-service-specific-credential --user-name APIuser --service-specific-credential-id "$cred"
            echo "🔐 Service-specific credential deleted: $cred"
        done
    else
        echo "📌 No service-specific credentials to delete"
    fi

    # Detach policies
    echo "  Detaching policies..."
    POLICIES=$(aws iam list-attached-user-policies --user-name APIuser --query 'AttachedPolicies[].PolicyArn' --output text)
    if [ -n "$POLICIES" ]; then
        for policy in $POLICIES; do
            aws iam detach-user-policy --user-name APIuser --policy-arn "$policy"
            echo "📝 Policy deleted: $policy"
        done
    else
        echo "📌 No policies to detach"
    fi

    # Delete user
    echo "  Deleting user..."
    aws iam delete-user --user-name APIuser
    echo "🙋🏻‍♀️ IAM User 'APIuser' deleted successfully"
else
    echo "📌 IAM User 'APIuser' does not exist"
fi

echo "=========================================="
echo ""
echo "=========================================="
echo "Setting up IAM User and Environment Variables"
echo "=========================================="

# Create IAM User "APIuser"
echo "Creating IAM User: APIuser..."
if aws iam create-user --user-name APIuser 2>/dev/null; then
    echo "✓ IAM User 'APIuser' created successfully"
else
    if aws iam get-user --user-name APIuser &>/dev/null; then
        echo "✓ IAM User 'APIuser' already exists"
    else
        echo "✗ Error: Failed to create IAM User 'APIuser'"
        exit 1
    fi
fi

# Attach AdministratorAccess policy
echo "Attaching AdministratorAccess policy..."
if aws iam attach-user-policy \
    --user-name APIuser \
    --policy-arn arn:aws:iam::aws:policy/AdministratorAccess 2>/dev/null; then
    echo "✓ AdministratorAccess policy attached successfully"
else
    # Check if policy is already attached (ignore error in this case)
    if aws iam list-attached-user-policies --user-name APIuser | grep -q "AdministratorAccess"; then
        echo "✓ AdministratorAccess policy already attached"
    else
        echo "✗ Error: Failed to attach AdministratorAccess policy"
        exit 1
    fi
fi

# Verify IAM User setup
echo "Verifying IAM User setup..."
aws iam get-user --user-name APIuser > /dev/null
aws iam list-attached-user-policies --user-name APIuser

# Create Access Key and capture output
echo "Creating Access Key for APIuser..."
ACCESS_KEY_OUTPUT=$(aws iam create-access-key --user-name APIuser 2>&1)
if [ $? -ne 0 ]; then
    echo "✗ Error: Failed to create Access Key"
    echo "Error details: $ACCESS_KEY_OUTPUT"
    exit 1
fi

# Extract AWS credentials from JSON output (store in separate variables for CloudFormation)
GENERATED_AWS_ACCESS_KEY_ID=$(echo "$ACCESS_KEY_OUTPUT" | jq -r '.AccessKey.AccessKeyId')
GENERATED_AWS_SECRET_ACCESS_KEY=$(echo "$ACCESS_KEY_OUTPUT" | jq -r '.AccessKey.SecretAccessKey')

# Validate extracted credentials
if [ -z "$GENERATED_AWS_ACCESS_KEY_ID" ] || [ "$GENERATED_AWS_ACCESS_KEY_ID" = "null" ]; then
    echo "✗ Error: Failed to extract AWS_ACCESS_KEY_ID"
    echo "Output: $ACCESS_KEY_OUTPUT"
    exit 1
fi

if [ -z "$GENERATED_AWS_SECRET_ACCESS_KEY" ] || [ "$GENERATED_AWS_SECRET_ACCESS_KEY" = "null" ]; then
    echo "✗ Error: Failed to extract AWS_SECRET_ACCESS_KEY"
    echo "Output: $ACCESS_KEY_OUTPUT"
    exit 1
fi

echo "✓ Access Key created successfully"
echo "  AWS_ACCESS_KEY_ID: ${GENERATED_AWS_ACCESS_KEY_ID:0:20}..."

# Create Bedrock Bearer Token (Service-Specific Credential)
echo "Creating Bedrock Bearer Token for APIuser..."
BEDROCK_TOKEN_OUTPUT=$(aws iam create-service-specific-credential --user-name APIuser --service-name bedrock.amazonaws.com --credential-age-days 10 2>&1)

if [ $? -ne 0 ]; then
    echo "✗ Error: Failed to create Bedrock Bearer Token"
    echo "Error details: $BEDROCK_TOKEN_OUTPUT"
    exit 1
fi

# Extract Bedrock Bearer Token from JSON output (store in separate variable for CloudFormation)
GENERATED_AWS_BEARER_TOKEN_BEDROCK=$(echo "$BEDROCK_TOKEN_OUTPUT" | jq -r '.ServiceSpecificCredential.ServiceCredentialSecret')

# Validate extracted token
if [ -z "$GENERATED_AWS_BEARER_TOKEN_BEDROCK" ] || [ "$GENERATED_AWS_BEARER_TOKEN_BEDROCK" = "null" ]; then
    echo "✗ Error: Failed to extract AWS_BEARER_TOKEN_BEDROCK"
    echo "Output: $BEDROCK_TOKEN_OUTPUT"
    exit 1
fi

echo "✓ Bedrock Bearer Token created successfully"
echo "  Token alias: $(echo "$BEDROCK_TOKEN_OUTPUT" | jq -r '.ServiceSpecificCredential.ServiceCredentialAlias')"
echo "  Expiration: $(echo "$BEDROCK_TOKEN_OUTPUT" | jq -r '.ServiceSpecificCredential.ExpirationDate')"

# Validate required environment variables
echo "Validating required environment variables..."

if [ -z "$REMOTE_SSH_PUBLIC_KEY" ]; then
    echo "✗ Error: REMOTE_SSH_PUBLIC_KEY environment variable is not set"
    echo "Please set it before running this script:"
    echo "  export REMOTE_SSH_PUBLIC_KEY='your-ssh-public-key'"
    exit 1
fi

if [ -z "$GITHUB_TOKEN" ]; then
    echo "✗ Error: GITHUB_TOKEN environment variable is not set"
    echo "Please set it before running this script:"
    echo "  export GITHUB_TOKEN='your-github-token'"
    exit 1
fi

if [ -z "$OPENAI_API_KEY" ]; then
    echo "✗ Error: OPENAI_API_KEY environment variable is not set"
    echo "Please set it before running this script:"
    echo "  export OPENAI_API_KEY='your-openai-api-key'"
    exit 1
fi

echo "✓ All required environment variables validated"
echo "✓ All environment variables set successfully"
echo "=========================================="

# Get AWS Account ID and Region
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
REGION=${AWS_REGION:-ap-northeast-2}

# S3 Bucket name for CloudFormation templates
S3_BUCKET_NAME="vscode-server-template-${ACCOUNT_ID}-${REGION}"

echo "=========================================="
echo "VSCode Server Stack Deployment"
echo "=========================================="
echo "Account ID: ${ACCOUNT_ID}"
echo "Region: ${REGION}"
echo "Stack Name: ${STACK_NAME}"
echo "Project Name: ${PROJECT_NAME}"
echo "Instance Type: ${INSTANCE_TYPE}"
echo "VSCode Server Version: ${VSCODE_SERVER_VERSION}"
echo "Deploy Project Resource: ${DEPLOY_PROJECT_RESOURCE}"
echo "Deploy Init Minimal: ${DEPLOY_INIT_MINIMAL}"
echo "S3 Bucket: ${S3_BUCKET_NAME}"
echo "=========================================="

# Check if S3 bucket exists, create if not
if aws s3 ls "s3://${S3_BUCKET_NAME}" 2>/dev/null; then
    echo "S3 bucket ${S3_BUCKET_NAME} already exists"
else
    echo "Creating S3 bucket ${S3_BUCKET_NAME}..."
    if [ "${REGION}" = "us-east-1" ]; then
        aws s3api create-bucket --bucket "${S3_BUCKET_NAME}" --region "${REGION}"
    else
        aws s3api create-bucket \
            --bucket "${S3_BUCKET_NAME}" \
            --region "${REGION}" \
            --create-bucket-configuration LocationConstraint="${REGION}"
    fi

    # Enable versioning for better template management
    echo "Enabling versioning on S3 bucket..."
    aws s3api put-bucket-versioning \
        --bucket "${S3_BUCKET_NAME}" \
        --versioning-configuration Status=Enabled

    # Enable encryption
    echo "Enabling encryption on S3 bucket..."
    aws s3api put-bucket-encryption \
        --bucket "${S3_BUCKET_NAME}" \
        --server-side-encryption-configuration '{
            "Rules": [{
                "ApplyServerSideEncryptionByDefault": {
                    "SSEAlgorithm": "AES256"
                }
            }]
        }'

    echo "S3 bucket ${S3_BUCKET_NAME} created successfully"
fi

echo "=========================================="
echo "Downloading CloudFormation template..."
echo "=========================================="

# Download template (force overwrite with -o flag)
curl -fsSL https://raw.githubusercontent.com/shkim4u/vscode-server/main/cloudformation/vscode-server-stack.yaml \
    -o /tmp/vscode-server-stack.yaml

echo "Template downloaded successfully"
echo "Template size: $(stat -f%z /tmp/vscode-server-stack.yaml 2>/dev/null || stat -c%s /tmp/vscode-server-stack.yaml) bytes"

echo "=========================================="
echo "Deploying CloudFormation stack..."
echo "=========================================="

# Deploy stack
aws cloudformation deploy \
    --stack-name "${STACK_NAME}" \
    --template-file /tmp/vscode-server-stack.yaml \
    --s3-bucket "${S3_BUCKET_NAME}" \
    --s3-prefix cloudformation-templates \
    --parameter-overrides \
      InstanceType="${INSTANCE_TYPE}" \
      VSCodeServerVersion="${VSCODE_SERVER_VERSION}" \
      GitHubAccessToken="${GITHUB_TOKEN}" \
      RemoteSSHPublicKey="${REMOTE_SSH_PUBLIC_KEY}" \
      ProjectName="${PROJECT_NAME}" \
      DeployProjectResource="${DEPLOY_PROJECT_RESOURCE}" \
      DeployInitMinimal="${DEPLOY_INIT_MINIMAL}" \
      AWSAccessKeyId="${GENERATED_AWS_ACCESS_KEY_ID}" \
      AWSSecretAccessKey="${GENERATED_AWS_SECRET_ACCESS_KEY}" \
      AWSBearerTokenBedrock="${GENERATED_AWS_BEARER_TOKEN_BEDROCK}" \
      OpenAIAPIKey="${OPENAI_API_KEY}" \
    --capabilities CAPABILITY_IAM \
    --region "${REGION}"

# Check deployment result
DEPLOY_EXIT_CODE=$?
if [ $DEPLOY_EXIT_CODE -ne 0 ]; then
    echo "=========================================="
    echo "✗ Deployment failed!"
    echo "=========================================="
    echo "CloudFormation deployment returned error code: $DEPLOY_EXIT_CODE"
    echo "Please check the CloudFormation console for detailed error information."
    exit 1
fi

echo "=========================================="
echo "✓ Deployment completed successfully!"
echo "=========================================="

# Get stack outputs
echo "Stack Outputs:"
aws cloudformation describe-stacks \
    --stack-name "${STACK_NAME}" \
    --region "${REGION}" \
    --query 'Stacks[0].Outputs[*].[OutputKey,OutputValue]' \
    --output table

echo ""
echo "🔎 Retrieving VSCode Server Instance ID..."
# VSCode Server Instance ID 조회
VSCODE_SERVER_INSTANCE_ID=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --query "Stacks[0].Outputs[?OutputKey=='VSCodeServerInstanceId'].OutputValue" \
  --region "${REGION}" \
  --output text)
echo "🏷️ VSCode Server Instance ID: "
echo "$VSCODE_SERVER_INSTANCE_ID"

echo ""
echo "🔎 Retrieving VSCode Server CloudFront Domain Name..."
# VSCodeServerCloudFrontDomainName 값 조회
VSCODE_SERVER_CLOUDFRONT_DOMAIN_NAME=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --query "Stacks[0].Outputs[?OutputKey=='VSCodeServerCloudFrontDomainName'].OutputValue" \
  --region "${REGION}" \
  --output text)

echo "🏡 VSCode Server CloudFront Domain Name: "
echo "$VSCODE_SERVER_CLOUDFRONT_DOMAIN_NAME"

# PASSWORD_SSM 값 조회
PASSWORD_SSM=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --query "Stacks[0].Outputs[?OutputKey=='VSCodeServerPasswordSSM'].OutputValue" \
  --region "${REGION}" \
  --output text)

echo ""
echo "🔎 Retrieving password from Parameter Store: $PASSWORD_SSM"
PASSWORD=$(aws ssm get-parameter \
  --name "$PASSWORD_SSM" \
  --with-decryption \
  --query "Parameter.Value" \
  --region "${REGION}" \
  --output text 2>/dev/null)

if [ $? -eq 0 ] && [ -n "$PASSWORD" ]; then
  echo "🚨 (주의) 아래 실습 환경 접속을 위한 액세스 코드는 유출되지 않도록 각별히 유의해 주시기 바랍니다!"
  echo "🔑 VSCode Server Access Code: $PASSWORD"
else
  echo "Error: Failed to retrieve password from Parameter Store"
  echo "Parameter name: $PASSWORD_SSM"
fi
